# docker-compose -f docker-compose.loadtest.yml up --build

x-app-common: &app-common
  build:
    context: .
    dockerfile: Dockerfile.loadtest
  volumes:
    - ./app:/app
  networks:
    - default
  restart: on-failure
  env_file:
    - .env
  depends_on:
    - redis

version: "3.2"
services:
  redis:
    image: redis:6.2-alpine
    # https://github.com/compose-spec/compose-spec/blob/master/deploy.md#restart_policy
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "6379:6379"
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - default

  celery:
    <<: *app-common
    command: celery
    depends_on:
      - redis

  webhook:
    <<: *app-common
    command: fastapi
    ports:
      - 9000:8000
      # - 8089:8089
    depends_on:
      - redis
      - celery

  flower:
    image: mher/flower:0.9.7
    command: ["flower", "--broker=redis://redis:6379", "--port=5555"]
    ports:
      - 5557:5555
    depends_on:
      - redis
      - webhook
    networks:
      - default

  # locust-master:
  #   image: locustio/locust
  #   ports:
  #     - "8089:8089"
  #   # volumes:
  #   #   - ./:/mnt/locust
  #   command: -f ./locustfile.py --master -H http://locust-master:8089

  # locust-worker:
  #   image: locustio/locust
  #   command: -f ./locustfile.py --worker --master-host locust-master
